### ISSUE TITLE
Remove signup graphic and text

### ISSUE THREAD

**Issue by robb-romans** [rackerlabs/docs-landing-page#161]
Signup link is deprecated and 404

Remove animated signup image
Remove signup button

![Screen Shot 2021-06-25 at 10 44 43 AM](https://user-images.githubusercontent.com/730187/123452264-dc756a00-d5a3-11eb-8805-cf05d876c6e8.png)

**Comment by codebyravi** [comment]
Fixed.

**Comment by robb-romans** [comment]
I'm not seeing the change
![image](https://user-images.githubusercontent.com/730187/123477348-89131400-d5c3-11eb-8249-e8925eb96ca1.png)

**Comment by robb-romans** [comment]
oic, the button is gone but the gif is still there. that's fine.
