### ISSUE TITLE
Mobile page eyebrow aligned oddly

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/docs-landing-page#2]
The eyebrow (the part that has the log in/buy now/status links) is malaligned in mobile (iPhone XR - Chrome)

![Image from iOS](https://user-images.githubusercontent.com/12717324/100894786-78158080-3482-11eb-89c0-d3bcd253c179.png)

**Comment by stephamon** [comment]
Yikes that's a huge image, sorry!

**Comment by codebyravi** [comment]
Fixed.

**Comment by Sterling463** [comment]
@stephamon can you confirm that this is fixed?

**Comment by stephamon** [comment]
@codebyravi @Sterling463 it looks great to me! Thanks!

**Comment by robb-romans** [comment]
Fixed
