### ISSUE TITLE
Page footer is aligned oddly

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/docs-landing-page#3]
The bottom footer on the page has some funky alignment going on:

sdk.rackspace:
![Screen Shot 2020-12-02 at 9 42 23 AM](https://user-images.githubusercontent.com/12717324/100895094-cc206500-3482-11eb-8a65-6d5faac37b14.png)

developer.rackspace:
![Screen Shot 2020-12-02 at 9 42 28 AM](https://user-images.githubusercontent.com/12717324/100895111-d17daf80-3482-11eb-8760-9788f2058047.png)

**Comment by codebyravi** [comment]
Fixed.

**Comment by Sterling463** [comment]
@stephamon can you verify this is fixed?

**Comment by stephamon** [comment]
@codebyravi @Sterling463 looks great! Thanks!
