### ISSUE TITLE
Change page title and intro

### ISSUE THREAD

**Issue by robb-romans** [rackerlabs/docs-landing-page#4]
Change from:
**Developer Documentation**
Whether you’re just getting started with the Rackspace Cloud or looking for reference on a product you’ve been using for a while, we’ve got the right documentation to get you on your way.

To:
**Solutions Documentation**
Whether you’re just getting started with our products and services, or looking for reference on something you’ve been using for a while, we’ve got the right documentation to get you on your way.

**Comment by codebyravi** [comment]
Updated.

**Comment by robb-romans** [comment]
not seeing the change. did you push?
