### ISSUE TITLE
Change Product Guides section and rearrange

### ISSUE THREAD

**Issue by robb-romans** [rackerlabs/docs-landing-page#6]
Change section Product Guides section and center it (remove SDKs & Tools category)

Product Guides category:
- Change title to: **Products and Services**
- Remove **APIS** graphic
- Change summary text to "Learn the capabilities of our solutions by exploring Getting Started, Reference, and Developer guides."
- Change link title to "Read solutions guides"
- Center this category on page

SDKs & Tools category:
- Remove this category entirely

**Comment by codebyravi** [comment]
Updated.
